version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fiber_test
      MONGO_INITDB_USERNAME: art
      MONGO_INITDB_PASSWORD: 1234
    ports:
      - "27017:27017"
